---
name: Build Container

"on":
  workflow_dispatch:

jobs:
  container:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install cross
        run: cargo install cross

      - name: Build aarch64 binary
        run: cross build --release --target aarch64-unknown-linux-gnu

      - name: Build x86_64 binary
        run: cross build --release --target x86_64-unknown-linux-gnu

      - name: Copy binaries to bin directory
        run: |
          mkdir bin
          cp target/aarch64-unknown-linux-gnu/release/netbox-oxidized-jsonfile bin/netbox-oxidized-jsonfile-arm64
          cp target/x86_64-unknown-linux-gnu/release/netbox-oxidized-jsonfile bin/netbox-oxidized-jsonfile-amd64

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/devon-mar/netbox-oxidized-jsonfile

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
